name: Rhult's Blog
description: Mostly about programming.
meta_description: "Rhult's Blog, Mostly about programming."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://rhult.github.io'
#google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'rhult'

# Details for the RSS feed generator
url:            'https://rhult.github.io'
author:         'Richard Hult'
authorTwitter:  'rhult'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
